### ISSUE TITLE
how to format code with prettier, stylua

### ISSUE THREAD

**Issue by itsuki0927** [lukas-reineke/lsp-format.nvim#29]
I want to ask how to use `prettier` to format code, I see that efm lsp is used in the documentation, but I don't use this, I just installed simple `tsserver`, `vuels`, `cssls` lsp, I don't see the specific usage in the documentation , can you provide a demo? 

lsp info: 
![WechatIMG2092](https://user-images.githubusercontent.com/40518195/158920699-856eda70-0d69-45d1-9614-4ccf621666fc.jpeg)

tsserver setup:
![WechatIMG2094](https://user-images.githubusercontent.com/40518195/158920878-b47bca3c-82fc-42d0-8086-fcb8ff626b32.jpeg)

on_attach: 
![WechatIMG2102](https://user-images.githubusercontent.com/40518195/158921239-e0d775a6-a1d6-47ee-82e8-ad3f5bf0ae80.png)

this is my code, but it's not work, am i missing something? and if I also want to format the lua file using stylua, What should we do?

**Comment by lukas-reineke** [comment]
lsp-format.nvim does not format itself. It just a wrapper for language servers.
So you need a language server that can format with `prettier` or `stylua`.
I use EFM for this. There are other options as well, like https://github.com/jose-elias-alvarez/null-ls.nvim

For how to configure them, please look at their documentation.
