### ISSUE TITLE
Why is ^M added automatically when formatting

### ISSUE THREAD

**Issue by lost4git** [lukas-reineke/lsp-format.nvim#30]
![image](https://user-images.githubusercontent.com/65008815/163187205-b7e754d8-5dcd-4720-85d2-63b12bd50828.png)

**Comment by lukas-reineke** [comment]
Those are dos line endings. Your LSP probably formats them for windows, because it is powershell.
https://en.wikipedia.org/wiki/Newline#Issues_with_different_newline_formats

This is not something this plugin has control over. You have to look at the LSP you are using to format.
