### ISSUE TITLE
Completely stopped working on latest master (v2.3.2)

### ISSUE THREAD

**Issue by Mange** [lukas-reineke/lsp-format.nvim#39]
Hi,

I'm not even sure how to debug this properly or where to start.

I pulled the latest version and now I can't format anymore, on any LSP.

Symptoms:

- Running `:Format` does nothing.
- Running `:lua vim.lsp.buf.formatting()` works.
- Running `:lua vim.lsp.buf.formatting_sync_seq()` works.
- Saving a file does not autoformat it.
- No messages or errors show up when starting, or when running any of the commands.

Here's my config:

```lua
-- packer
  use "lukas-reineke/lsp-format.nvim"
```

```lua
local lspformat = require("lsp-format")

-- …

  lspformat.setup()
  -- lspformat.setup {
  --   typescript = {
  --     exclude = { "tsserver" },
  --   },
  --   lua = {
  --     exclude = { "sumneko_lua" },
  --   },
  --   ruby = {
  --     -- Use standardrb via null-ls instead.
  --     exclude = { "solargraph" },
  --   },
  -- }
  -- lspformat.disable { args = "markdown" }
  -- lspformat.disable { args = "vimwiki" }
  -- lspformat.disable { args = "eruby" } -- completely breaks in most formatters

-- LSP servers configured like this:
-- { on_attach = on_attach }

local function on_attach(...)
  lspformat.on_attach(...)
  on_attach_without_formatting(...)
end
```

I use `null-ls` for most formatting stuff.

Running nvim nightly `NVIM v0.8.0-dev+27-g5c4ec25478`

**Comment by Mange** [comment]
I went to my checked out package and jumped between different versions.

It broke completely on v2.3.0, same symptoms as listed in description.

The version before it, v2.2.3 still works, but only when formatting a saved buffer. Running `:Format` on an unchanged buffer does nothing. Seems this is a separate problem.

**Comment by lukas-reineke** [comment]
can you make a minimal `init.lua` file that reproduces this?

**Comment by bmulholland** [comment]
I just tried installing for the first time and formatting is not working for me either.

**Comment by bmulholland** [comment]
Also confirm that this PR broke `:Format`: https://github.com/lukas-reineke/lsp-format.nvim/pull/33/files

Also seems that the default config doesn't fulfill its promise of formatting on save; I have to manually run Format, at least for Lua. Will have to check why.

**Comment by lukas-reineke** [comment]
Alright, let's try to add some logging to debug then.

The first obvious ones are here https://github.com/lukas-reineke/lsp-format.nvim/blob/2fcb2c99d8a833190d7bb577ed4ec4a304926300/lua/lsp-format/init.lua#L166 log what is send to the server

And here https://github.com/lukas-reineke/lsp-format.nvim/blob/2fcb2c99d8a833190d7bb577ed4ec4a304926300/lua/lsp-format/init.lua#L124 the result that comes back

**Comment by bmulholland** [comment]
I figured it out, at least for me. What has changed is the behaviour when LSP on_attach is not properly configured. The fix is to properly attach lsp-format to your LSPs.

Specifically, if an LSP is missing the `require("lsp-format").on_attach(client)` requirement, as mine was, then on commit `db45b37` autoformat will not work (and perhaps never did). **`:Format` will, though**.

The commit that "broke" `:Format` is actually `4ba2f95f78af8b2d4d99c8ebe32074c529101b32` (I bisected). And this makes sense, considering that commit says "Don't format with client if `on_attach` was not called for that client"

**Comment by lukas-reineke** [comment]
👍 
Yes the behavior changed, but I consider it a bug that this worked before.
To be used for formatting, each LSP now needs to be attached individually.
Before it used all servers once it was called for one server on the buffer.

**Comment by bmulholland** [comment]
> I consider it a bug that this worked before

Me too :). Thanks again.

**Comment by Mange** [comment]
I created a badly formatted shell script and tried to `:Format` it with some logging added on the previously mentioned lines. Here's what I got:

```lua
-- client.request call
{
  bufnr = 1,
  handler = <function 1>,
  method = "textDocument/formatting",
  params = {
    options = {
      insertSpaces = true,
      tabSize = 2
    },
    textDocument = {
      uri = "file:///home/mange/Projects/dotfiles/foo.sh"
    }
  }
}

-- _handler being called with
{
  ctx = {
    bufnr = 1,
    client_id = 1,
    method = "textDocument/formatting",
    params = {
      options = {
        insertSpaces = true,
        tabSize = 2
      },
      textDocument = {
        uri = "file:///home/mange/Projects/dotfiles/foo.sh"
      }
    }
  },
  err = {
    code = -32601,
    message = "Unhandled method textDocument/formatting",
    <metatable> = {
      __tostring = <function 1>
    }
  }
}
```

I have two LSPs for shells: `bashls` and `null-ls`. `bashls` does not handle formatting, so the error makes sense. However, I would expect the handler and formatting to be called again for `null-ls`, but there's only this one call.

I then tried disabling `bashls` and restarted so only `null-ls` was attached. If I run `:Format` now nothing is logged at all.

By stepping through all the conditionals I figured out that the problem was that `M.buffers` were empty.

…aaaand, here we are. Turns out I set up `on_attach` on all LSP servers but `null-ls`, since it was placed in a different section much further down and I forgot to check it.

So another one one the pile; misconfiguration in the PEBKAC module. :sweat_smile:
