### ISSUE TITLE
Can you give us a clearer example of how to use the on_attach function?

### ISSUE THREAD

**Issue by FrancoEnriqueLimonDiaz** [lukas-reineke/lsp-format.nvim#48]
I want to format html, css, sass, javascript and ruby and, I have something like this! Can you give a code snippet to format these languages?, thanks. 
![info-lsp-config](https://user-images.githubusercontent.com/85474646/171760489-ae2aa160-f47c-4c88-a369-49abeb57caf8.png)

**Comment by lukas-reineke** [comment]
> I want to format html, css, sass, javascript and ruby

Then you have to set up LSP server for those languages. lsp-format does not know or care what language you are using.
You just have to call it with the LSP client of each server you use.

The example in the readme is for gopls, that is the Golang LSP

```lua
require "lspconfig".gopls.setup { on_attach = require "lsp-format".on_attach }
```

If you want to use it with Javascript, you need tsserver, etc.

```lua
require "lspconfig".tsserver.setup { on_attach = require "lsp-format".on_attach }
```

**Comment by FrancoEnriqueLimonDiaz** [comment]
> > I want to format html, css, sass, javascript and ruby
> 
> Then you have to set up LSP server for those languages. lsp-format does not know or care what language you are using. You just have to call it with the LSP client of each server you use.
> 
> The example in the readme is for gopls, that is the Golang LSP
> 
> ```lua
> require "lspconfig".gopls.setup { on_attach = require "lsp-format".on_attach }
> ```
> 
> If you want to use it with Javascript, you need tsserver, etc.
> 
> ```lua
> require "lspconfig".tsserver.setup { on_attach = require "lsp-format".on_attach }
> ```
