### ISSUE TITLE
support sync save for global

### ISSUE THREAD

**Issue by junnplus** [lukas-reineke/lsp-format.nvim#50]
I need to set synchronization options for different filetypes, is there a way to set them globally?

**Comment by lukas-reineke** [comment]
No, there is no built in way to set options globally.

But you could script this pretty easly like so

```lua
local config = {}
for _, v in pairs(vim.fn.getcompletion("", "filetype")) do
    config[v] = { sync = true }
end
require("lsp-format").setup(config)
```
