### ISSUE TITLE
messes up files when writing into multiple files at once with multiple formating lsp providers

### ISSUE THREAD

**Issue by vitaly** [lukas-reineke/lsp-format.nvim#58]
how to reproduce:

- install sumneko lua-language-server
- install stylua
- install null-ls and enable stylua formatter
- open about 50 lua files with, e.g. `vim lua/**/*.lua`
- run `bufdo w`

vim will start writing into all those files and lsp-format will endup with file contents mixed between the files. e.g.
file `foo` will have content of file `bar`, which, in turn will have content of file `baz` etc.

**Comment by lukas-reineke** [comment]
I found some issues when writing a buffer that is not the current one, I made a PR here https://github.com/lukas-reineke/lsp-format.nvim/pull/59
But none of those issues would write content from one buffer into another, and I also can't reproduce that :thinking: 

Can you check if the PR changes anything?

**Comment by lparry** [comment]
Is there a config option to _not_ format anything except the focused buffer? I'm not sure if it's exactly the same thing as this issue, but I seem to get stuck in loops where if I save a file, every other buffer ends up with changes preventing `:q`, so I change buffer, `:w` and now every buffer is touched again. non-focused formatting just feels unhelpful

**Comment by lukas-reineke** [comment]
this is a different issue, and it should not happen.
Can you make a new ticket with steps to reproduce?
