### ISSUE TITLE
Enabling eslint

### ISSUE THREAD

**Issue by MaximilianGaedig** [lukas-reineke/lsp-format.nvim#67]
Thank you very much for creating this plugin :)

I was configuring it today and I ran into some problems enabling eslint (and disabling tsserver) for formatting, but finally found a solution and wanted to share it as other people might run into the same problem.
I had to add
```lua
  if client.name == 'tsserver' then
    -- Disable formatting for typescript 
    client.server_capabilities.documentFormattingProvider = false -- for lsp-format
  elseif client.name == 'eslint' then
    -- Enable formatting for eslint
    client.server_capabilities.documentFormattingProvider = true -- for lsp-format
  end
```
in my on_attach function, then eslint was enabled, tsserver had to be disabled because otherwise eslint ran first and it corrected its issues then tsserver formatted the file while ignoring my eslint rules.
Such problems were documented already but this plugin required a bit of a different solution as the solution normally was to set `document_formatting` instead of `documentFormattingProvider`.

This seems a bit hacky, so if there is a better solution please tell me!

**Comment by lukas-reineke** [comment]
This is not how you should do it.

There are 2 options.

1. To completely disable an LSP from formatting, don't call lsp-formats attach function for that LSP at all.

2. To exclude an LSP for specific filetypes, use `:help lsp-format-exclude`

**Comment by MaximilianGaedig** [comment]
> This is not how you should do it.
> 
> There are 2 options.
> 
> 1. To completely disable an LSP from formatting, don't call lsp-formats attach function for that LSP at all.
> 2. To exclude an LSP for specific filetypes, use `:help lsp-format-exclude`
ah yeah true the exclusion should be done differently, but what about the eslint enabling? Is there a better solution?

**Comment by lukas-reineke** [comment]
> but what about the eslint enabling

There is no concept of enabling in lsp-format. When you attach a server, and it is not explicitly excluded, it is enabled.

**Comment by MaximilianGaedig** [comment]
> > but what about the eslint enabling
> 
> 
> 
> There is no concept of enabling in lsp-format. When you attach a server, and it is not explicitly excluded, it is enabled.

the server has to have that "document/textFormatting" ability tho, and eslint has that but doesn't report it, so you need to override it

**Comment by lukas-reineke** [comment]
I understand. Yeah this is a problem with the eslint LSP server. I don't have any better suggestion than what you are already doing
