### ISSUE TITLE
Does lsp-format supports `shfmt` & `stylua` ?

### ISSUE THREAD

**Issue by lucazz** [lukas-reineke/lsp-format.nvim#68]
Hello there, everyone!

This is a fantastic plug-in, btw. Thanks for writing that. 

I was just wondering how one would wire in formatters like `shfmt` and `stylua`.

I use Mason to install those and these are the only ones missing from my setup at this moment.

**Comment by lukas-reineke** [comment]
You need to wrap those formatters in an LSP.

I personally use https://github.com/mattn/efm-langserver

And there is https://github.com/jose-elias-alvarez/null-ls.nvim
