### ISSUE TITLE
Format on auto save

### ISSUE THREAD

**Issue by miladabc** [lukas-reineke/lsp-format.nvim#69]
Thanks for your work on this plugin,  
I was wondering if it is possible to format on auto save, I have this autocmd and your plugin does not format after this.
```lua
vim.api.nvim_create_autocmd("BufLeave", {
	group = vim.api.nvim_create_augroup("AutoSave", { clear = true }),
	callback = function(event)
		vim.api.nvim_command("update")
	end,
})
```

**Comment by lukas-reineke** [comment]
This is probably because autocommands are not nested by default. Take a look at `:help autocmd-nested`
