### ISSUE TITLE
`lsp-format.nvim` changes the buffer when write to file twice during a short time of period

### ISSUE THREAD

**Issue by zhou13** [lukas-reineke/lsp-format.nvim#71]
I am not sure how to create a reproducible test case but this is what I observed when I
1. make some changes to the buffer
2. save the file and trigger the format
3. make some edits again
4. save the file again
5. If the format process from 2 finished after 4, the buffer will be updated with the result from 2, overriding my edit from 3.

**Comment by lukas-reineke** [comment]
This should be fixed
