### ISSUE TITLE
 If two files are edited and saved at the same time (:wa), the contents of one file will be overwritten by the contents of the other

### ISSUE THREAD

**Issue by ryoppippi** [lukas-reineke/lsp-format.nvim#74]
If two files are edited and saved at the same time (:wa), the contents of one file will be overwritten by the contents of the other

https://github.com/lukas-reineke/lsp-format.nvim/assets/1560508/71157391-e86e-4675-bdef-a76c5f7d3f00

Here is my config for lsp-format

```lua
local spec = {
  "lukas-reineke/lsp-format.nvim",
  opts = { sync = true },
  enabled = true,
  init = function()
    local on_attach = require("core.plugin").on_attach
    on_attach(function(client, _)
      local enableFormat = client.server_capabilities.documentFormattingProvider
      if enableFormat then
        require("lsp-format").on_attach(client)
        -- vim.cmd([[
        --       cabbrev wq execute "Format sync" <bar> wq
        --       cabbrev wqa bufdo execute "Format sync" <bar> wa <bar> q
        --     ]])
      end
    end)
  end,
}
return spec
```

**Comment by lukas-reineke** [comment]
I cannot reproduce this.
Can you make a minimal config and steps to cause the issue?

**Comment by ryoppippi** [comment]
Thanks.
I made minimal config, but I also cannot reproduce.
I will investigate the cause a little more.

**Comment by towry** [comment]
@lukas-reineke While attempting to save two tsx files today, I ran into this same issue!

**Comment by towry** [comment]
branch bug/writing-inactive-buffer not work.

**Comment by FelipeLema** [comment]
forked [here](https://codeberg.org/FelipeLema/lsp-format.nvim) with a fix... seems to be working

**Comment by lukas-reineke** [comment]
Thanks,

I think I probably had already fixed this in #59 but I forgot to merge the PR :man_facepalming: 

I made a nicer version now in #75 
Can someone check if this does actually fix it?

**Comment by ryoppippi** [comment]
Looks good!

**Comment by lukas-reineke** [comment]
Made a new release

Please open the issue again if it is still broken

**Comment by Invertisment** [comment]
Today I updated my plugins and it fails with an error of `get_clients` because my function doesn't allow that.
How do I debug this? I downgraded this plugin to `v2.5.1` and it doesn't fail anymore :shrug:

**Comment by lukas-reineke** [comment]
Sorry, `get_clients` is nightly only. I released a fix.

**Comment by ryoppippi** [comment]
Hi!
I still got this error.

**Comment by madhermit** [comment]
Getting this error as well with commit version `31fc250a412ab24555b389f61fac0330f6bb7660`
