### ISSUE TITLE
No way to tell if auto-formatting is enabled

### ISSUE THREAD

**Issue by elken** [lukas-reineke/lsp-format.nvim#86]
_As far as I can tell_, there's no exposed API for determining if the current buffer will autosave.

It would be useful for me to have a modeline indicator so I can know before saving. Happy to submit a PR if it's easier for you, I figured you'd probably know the most sensible way to expose this though.

Thanks for a great package!

**Comment by lukas-reineke** [comment]
You can check `require('lsp-format').disabled` for if the plugin is disabled globally, and `require('lsp-format').disabled_filetypes[vim.bo.filetype]` for the current filetype.
And you can also check `require('lsp-format').buffers[vim.api.nvim_get_current_buf()]` if there are any clients attached to a buffer.

**Comment by elken** [comment]
Huh, when I inspected the object before and after disabling they were both identical but okay I'll try that :smile:

**Comment by elken** [comment]
Yeah after running toggle twice, enable then disable I get

![image](https://github.com/lukas-reineke/lsp-format.nvim/assets/2872862/1ca41b5f-9612-4b23-b945-ca3f4d82b16c)

**Comment by lukas-reineke** [comment]
If you want to see if the plugin is disabled globally `FormatToggle`, you need to check `require('lsp-format').disabled`

**Comment by elken** [comment]
> If you want to see if the plugin is disabled globally `FormatToggle`, you need to check `require('lsp-format').disabled`

Is it not handled per-buffer?

**Comment by lukas-reineke** [comment]
> Is it not handled per-buffer?

No, it's not. Only globally, or per filetype.

**Comment by elken** [comment]
Ahh my bad then, thanks anyway!
