### ISSUE TITLE
Formatting results are occasionally applied to the wrong file

### ISSUE THREAD

**Issue by loganswartz** [lukas-reineke/lsp-format.nvim#92]
When editing 2 or more different files, occasionally the formatting result from one file will be applied to the previous file instead of the current file. I think this issue is either related to, or the same as, both #58 and #71. However, unlike those 2 issues, I was able to create a mostly consistent minimal reproduction of the bug, which you can see [here](https://github.com/loganswartz/lsp-format-multi-file-formatting-bug).

I added some further notes and observations in the README of that repo, but take them with a grain of salt, as I haven't exhaustively tested those speculations. That reproduction works pretty reliably for me, but since it seems to be timing related, you may have to coerce it into working on your environment by modifying the delays.

**Comment by lukas-reineke** [comment]
Thanks for the reproduction repo
The issue was `vim.lsp.util.make_formatting_params`. It has `0` buffer hardcoded for generating the URI for the buffer. So even though the buffer numbers are correct, the URI was wrong..

I released a fix now
